# Generated by Django 3.1.5 on 2021-01-10 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1024)),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('secret', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
