# Generated by Django 3.1.5 on 2021-01-10 16:54

from django.db import migrations, models
import link.validators


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=None, max_length=1024, validators=[link.validators.url_exists]),
            preserve_default=False,
        ),
    ]
